### PR TITLE
Use SDCard module from MicroPython (introduced in version 1.12)

### PR DESCRIPTION
**Pull request by kratz00**
For more information, see: https://github.com/micropython/micropython/releases/tag/v1.12

### CODE REVIEW

**Comment by nitko12** [comment]
I'll merge this into dev and will eventually merge to master :)

**Comment by nitko12** [comment]
For some reason after adding these commits esp crashes after trying to run a program the second time, master works fine?

**Comment by kratz00** [comment]
@nitko12 What MicroPython version and program are you testing with?
I can test the *dev* branch later today.

**Comment by nitko12** [comment]
I've used bin file in the repo at this commit b72435144717b97e0d454a55e362a0eddd313f5a 

For some reason I can't run any code after running an example unless I reset the Inkplate, have you experienced anything similiar?

**Comment by kratz00** [comment]
This should be *esp32spiram-20210418-v1.15.bin* then, see https://github.com/micropython/micropython/issues/7352
I am using MicroPython v1.17. The situation is a little better, there are no crashes, but a SD card can only be initialized/mounted once (see https://github.com/micropython/micropython/issues/7414). After a reboot a SD card can be initialized/mounted again.

**Pull request merged**
